import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (


<Router>
  <Sid />
  <Routes>
    <Route path="/dashboard" element={<DashboardPage />} />
    <Route path="/tasks" element={<TasksPage />} />
    <Route path="/profile" element={<ProfilePage />} />
  </Routes>
</Router>

  );
}
